@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzY3NjYzMDQ1LCJleHAiOjE3Njc2NjY2NDV9.3RqkIwC9BGtFyBaOb1RxGGZ7vUBpfBtxesJU9e-j_v0
###프로젝트 멤버 조회
GET http://localhost:3000/projects/16/users
Authorization: Bearer {{accessToken}}

###프로젝트에서 유저 제외하기
DELETE http://localhost:3000/projects/16/users/11
Authorization: Bearer {{accessToken}}

###프로젝트에 멤버 초대
POST http://localhost:3000/projects/16/invitations
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "email" : "pkeonyz@gmail.com"
}

###멤버 초대 수락
POST http://localhost:3000/invitations/12/accept
Authorization: Bearer {{accessToken}}

###멤버 초대 삭제
DELETE http://localhost:3000/invitations/8
Authorization: Bearer {{accessToken}}