@url = http://localhost:3001
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzY3ODM0ODk0LCJleHAiOjE3Njc4Mzg0OTR9.x5xnFC2up6JGBXeh7R115aKQ_KRy9hipFmR9bkLdA28
###프로젝트 생성
POST {{url}}/projects
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "프로젝트 1",
  "description": "프로젝트 1 설명"
}

###프로젝트 조회
GET {{url}}/projects/19
Authorization: Bearer {{accessToken}}


###프로젝트 수정

PATCH {{url}}/projects/4
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "수정된 프로젝트",
  "description": "수정된 프로젝트 입니다."
}

###프로젝트 삭제
DELETE {{url}}/projects/19
Authorization: Bearer {{accessToken}}