@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3NjczNTEwMDEsImV4cCI6MTc2NzM1NDYwMX0.RqfIH0PgLcCTtj21tyKPNLB0p19R-s5PbjjJm7Lkqtg
POST http://localhost:3000/projects
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "프로젝트 1",
  "description": "프로젝트 1 설명"
}

###
GET http://localhost:3000/projects/2
Authorization: Bearer {{accessToken}}

###
PATCH http://localhost:3000/projects/13
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "수정된 프로젝트",
  "description": "수정된 프로젝트 입니다."
}

###
DELETE http://localhost:3000/projects/13
Authorization: Bearer {{accessToken}}