@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzY3ODUzODk5LCJleHAiOjE3Njc4NTc0OTl9._hh8OsfPdJEE6J6oSug1clCJv6ybrwIs9s24VdT-Czs
GET http://localhost:3001/projects/22/tasks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
POST http://localhost:3001/projects/22/tasks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    	"title": "string",
	"startYear": 2025,
	"startMonth": 1,
	"startDay": 7,
	"endYear": 2025,
	"endMonth": 1,
	"endDay": 10,
	"status": "TODO",
	"tags": [],
	"attachments":[]
}

###
GET http://localhost:3001/tasks/3
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
PATCH http://localhost:3001/tasks/3
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
 "description":"할 일 수정입니다."
}

###
DELETE http://localhost:3001/tasks/3
Content-Type: application/json
Authorization: Bearer {{accessToken}}
